"""make expense date required

Revision ID: 62f5ebffcd44
Revises: 6af46bd51fff
Create Date: 2026-07-19 15:58:22.605489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f5ebffcd44'
down_revision: Union[str, Sequence[str], None] = '6af46bd51fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.alter_column(
            "expense_date",
            existing_type=sa.Date(),
            nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.alter_column(
            "expense_date",
            existing_type=sa.Date(),
            nullable=True
        )
    # ### end Alembic commands ###
